top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/http
builddir     = /home/pi/httpd-2.4.29/modules/http
VPATH        = /home/pi/httpd-2.4.29/modules/http

include $(top_srcdir)/build/special.mk

