top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/os
builddir     = /home/pi/httpd-2.4.29/os
VPATH        = /home/pi/httpd-2.4.29/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
