top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/server/mpm/event
builddir     = /home/pi/httpd-2.4.29/server/mpm/event
VPATH        = /home/pi/httpd-2.4.29/server/mpm/event
include $(top_srcdir)/build/special.mk
