top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/echo
builddir     = /home/pi/httpd-2.4.29/modules/echo
VPATH        = /home/pi/httpd-2.4.29/modules/echo

include $(top_srcdir)/build/special.mk

