top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/mappers
builddir     = /home/pi/httpd-2.4.29/modules/mappers
VPATH        = /home/pi/httpd-2.4.29/modules/mappers

include $(top_srcdir)/build/special.mk

