top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/core
builddir     = /home/pi/httpd-2.4.29/modules/core
VPATH        = /home/pi/httpd-2.4.29/modules/core

include $(top_srcdir)/build/special.mk

