top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/arch/unix
builddir     = /home/pi/httpd-2.4.29/modules/arch/unix
VPATH        = /home/pi/httpd-2.4.29/modules/arch/unix

include $(top_srcdir)/build/special.mk

