top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/cache
builddir     = /home/pi/httpd-2.4.29/modules/cache
VPATH        = /home/pi/httpd-2.4.29/modules/cache

include $(top_srcdir)/build/special.mk

