top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/filters
builddir     = /home/pi/httpd-2.4.29/modules/filters
VPATH        = /home/pi/httpd-2.4.29/modules/filters

include $(top_srcdir)/build/special.mk

