top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/examples
builddir     = /home/pi/httpd-2.4.29/modules/examples
VPATH        = /home/pi/httpd-2.4.29/modules/examples
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
