top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/generators
builddir     = /home/pi/httpd-2.4.29/modules/generators
VPATH        = /home/pi/httpd-2.4.29/modules/generators

include $(top_srcdir)/build/special.mk

