top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/loggers
builddir     = /home/pi/httpd-2.4.29/modules/loggers
VPATH        = /home/pi/httpd-2.4.29/modules/loggers

include $(top_srcdir)/build/special.mk

