top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/server/mpm
builddir     = /home/pi/httpd-2.4.29/server/mpm
VPATH        = /home/pi/httpd-2.4.29/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
