top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/aaa
builddir     = /home/pi/httpd-2.4.29/modules/aaa
VPATH        = /home/pi/httpd-2.4.29/modules/aaa

include $(top_srcdir)/build/special.mk

