top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules/metadata
builddir     = /home/pi/httpd-2.4.29/modules/metadata
VPATH        = /home/pi/httpd-2.4.29/modules/metadata

include $(top_srcdir)/build/special.mk

