top_srcdir   = /home/pi/httpd-2.4.29
top_builddir = /home/pi/httpd-2.4.29
srcdir       = /home/pi/httpd-2.4.29/modules
builddir     = /home/pi/httpd-2.4.29/modules
VPATH        = /home/pi/httpd-2.4.29/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

